#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Michel Mattos"
email = "7696411+michelmattos@users.noreply.github.com"

[ui]
# Don't use pager - show output directly in terminal
paginate = "never"

editor = "hx"
diff-editor = ":builtin"
relative-timestamps = true

[remotes.origin]
# Automatically track all remote bookmarks
auto-track-bookmarks = "glob:*"
